### ISSUE TITLE
using "KUBECONFIG=~/ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec5 env=wec5" created everything but the syncerconfigs for both wec5 and wec6

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1072]
### Describe the bug

I found there were no syncerconfigs in the MBs after running 

```KUBECONFIG=ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec5 env=wec5```
and
```KUBECONFIG=ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec6 env=wec6```

### Steps To Reproduce

1. install kubestellar via helm from main branch
2. run get-external-config
3. run 'KUBECONFIG=ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec5 env=wec5'
4. run 'KUBECONFIG=ks.config kubectl ws root:espw:<your mb here>'
5. get escfg

observe - no syncer config

### Expected Behavior

I expect a syncerconfig to be created.  I created 1 myself using 

```
apiVersion: edge.kubestellar.io/v1alpha1
kind: SyncerConfig
metadata:
  name: the-one
spec:
  namespaceScope: {}
#  namespaceScope:
#    namespaces:
#    - data-science
#    - kuberay-operator
#    - mcad
#    - opendatahub
#    - openshift-operators
#    - openshift-operators-redhat
#  resources: {}
```
