### ISSUE TITLE
bug: updated syncerconfig to remove namespaces, yet syncer continues to pull names of namespaces previously defined

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1073]
### Describe the bug

I added a syncerconfig manually that looks like

```
apiVersion: edge.kubestellar.io/v1alpha1
kind: SyncerConfig
metadata:
  name: the-one
spec:
  namespaceScope: {}
  namespaceScope:
    namespaces:
    - data-science
    - kuberay-operator
    - mcad
    - opendatahub
    - openshift-operators
    - openshift-operators-redhat
  resources: {}```

I uncommented the lines above and the syncer output changed to show namespaces were being inspected for content.  I then changed back to the content above - which should match all namespaces, 

```
apiVersion: edge.kubestellar.io/v1alpha1
kind: SyncerConfig
metadata:
  name: the-one
spec:
  namespaceScope: {}
#  namespaceScope:
#    namespaces:
#    - data-science
#    - kuberay-operator
#    - mcad
#    - opendatahub
#    - openshift-operators
#    - openshift-operators-redhat
#  resources: {}
```

and the syncer continued to spit out the same output it did when the namespaces were enumerated


### Steps To Reproduce

1. add a syncerconfig to an mb with file from description that matches all namespaces
2. observe syncer output
3. update the same syncerconfig with specific namespaces
4. observe syncer output
5. update the same syncerconfig back to matching all namespaces
6. observe output

### Expected Behavior

I expect the syncer log output to change based on the selectors in the syncerconfig

### Additional Context

_No response_
