### ISSUE TITLE
feature: add denaturing for Service in controllers

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1451]
### Feature Description

This is a feature that is required when switching from kcp to KubeFlex-managed API servers. 

A regular Kube API server sets cluster networking-dependent fields that should not be propagated down to the WECs.

This can be tested in a KubeFlex-backed space:

Apply a service:
```
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
 ``` 
After applying the service, several fields are filled in with values that are specific to the network config for the API server in the WDS.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  clusterIP: 10.96.51.158
  clusterIPs:
  - 10.96.51.158
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31429
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  sessionAffinity: None
  type: NodePort
 ``` 
 
 The values on these fields are not valid in most cases for the target WEC.  This behavior cannot be controlled by disabling kube controllers on the WDS space.

### Proposed Solution

Need to nullify those fields in placement translator when using non-KCP based partially denatured spaces such as KubeFlex.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
This is taken care of in new 0.20 code - see https://github.com/kubestellar/kubestellar/blob/971986355b75adec42f602e27f73a6393ad828b9/pkg/ocm/ocm.go#L87-L91

@nirrozenbaum  @vMaroon  : We just have to make sure this is also preserved in the new transport code

**Comment by nirrozenbaum** [comment]
@pdettori noted to verify we don't miss this.
I think the best thing to do in order to validate it's preserved is to add e2e test that covers this.
shouldn't be a big effort considering we already have some e2e tests.. just need to distribute a service as above.
@ezrasilvera @effi-ofer wdyt? 

@pdettori as a side question - what happens if we don't nullify these fields? is the agent failing to apply the service on the WEC? do you know if there is an error and what is the error?

**Comment by nirrozenbaum** [comment]
I'm reopening the issue and adding pluggable transport label to make sure we don't miss it.
after validating it's working (or at least adding e2e to test) we can close.

**Comment by MikeSpreitzer** [comment]
"denaturing" means removing behavior associated with objects. That would be possible if we pursued the denaturing proxy that I started a year ago. Absent that: if we store these objects undisguised in a kube apiserver then it will apply the behavior that it applies, and we will have to apply compensating behavior (scrubbing) in the distribution process.

**Comment by pdettori** [comment]
@nirrozenbaum : re your questions:

> what happens if we don't nullify these fields? is the agent failing to apply the service on the WEC? do you know if there is an error and what is the error?


When applying a service, it gets propagated to the OCM mailbox namespace but not to the target cluster.

Scenario:

1. Apply service to wds1:

```
kubectl --context wds1 apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081   
  type: NodePort
EOF
```

Apply placement:

```
kubectl --context wds1 apply -f - <<EOF
apiVersion: edge.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: hello-world-placement
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - labelSelectors:
    - matchLabels: {"app":"hello-world"}
EOF
```

Check manifest work:

```
kubectl --context imbs1 describe manifestworks -n cluster1 v1-service-default-hello-world
```
The service was is copied to the OCM mailbox namespace (cluster1) but the service has been assigned a range of IPs in WDS1:

```
Resource Status:
    Manifests:
      Conditions:
        Last Transition Time:  2023-12-11T02:50:55Z
        Message:               Failed to apply manifest: Service "hello-world" is invalid: spec.clusterIPs: Invalid value: []string{"10.108.168.179"}: failed to allocate IP 10.108.168.179: the provided IP (10.108.168.179) is not in the valid range. The range of valid IPs is 10.96.0.0/16
        Reason:                AppliedManifestFailed
        Status:                False
        Type:                  Applied
        Last Transition Time:  2023-12-11T02:50:55Z
        Message:               Resource is not available
        Reason:                ResourceNotAvailable
        Status:                False
        Type:                  Available
``` 
The service gets assigned those IPs but the range is different in the target cluster.
