### ISSUE TITLE
bug: wantSingletonReportedState in edgeplacement does not update status for deployment

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1500]
### Describe the bug

I am using an edgeplacement with `wantSingletonReportedState: true` to deliver a deployment to workload clusters. The deployment gets delivered but the status of the deployment on ks-core does not get updated.

### Steps To Reproduce

1. Run the steps in https://docs.kubestellar.io/release-0.14/Getting-Started/user-quickstart-kind/ up to step 4.
2. Apply the following edge placement:
```
KUBECONFIG=ks-core.kubeconfig kubectl apply -f - <<EOF
apiVersion: edge.kubestellar.io/v2alpha1
kind: EdgePlacement
metadata:
  name: ep2
spec:
  locationSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - apiGroup: "apps"
    resources: [ "deployments" ]
    namespaces: [ "*" ]
    objectNames: [ "*" ]
    labelSelectors:
    - matchLabels: {"app":"foo"}
  wantSingletonReportedState: true  
EOF
```
3. Apply the following deployment:
```
KUBECONFIG=ks-core.kubeconfig kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ks-deployment2
  labels:
    app: foo
spec:
  selector: {matchLabels: {app: common} }
  template:
    metadata:
      labels: {app: common}
    spec:
      containers:
      - name: httpd
        image: public.ecr.aws/docker/library/httpd:2.4
        ports:
        - name: http
          containerPort: 80
          hostPort: 8090
          protocol: TCP
EOF
```
4. Check deployment is started on both clusters:
```
$ KUBECONFIG=~/.kube/config kubectl --context ks-edge-cluster1 get deployments.apps
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
ks-deployment2   1/1     1            1           9s
$ KUBECONFIG=~/.kube/config kubectl --context ks-edge-cluster2 get deployments.apps
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
ks-deployment2   1/1     1            1           17s
```
5. Check deployment on ks-core:
```
$ KUBECONFIG=ks-core.kubeconfig kubectl get deployments.apps ks-deployment2
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
ks-deployment2   0/0     0            0           109s
```
The deployment does not have a status. 

### Expected Behavior

The deployment on ks-core shows a status from one of the two clusters (perhaps chosen in a deterministic way - by name alphabetically ). Could the problem be that both clusters are selected by the location selector ? Does the user need to ensure (by working out on the labels) that only one cluster is selected for the `wantSingletonReportedState` to work ?
