### ISSUE TITLE
bug: A MutatingWebhookConfiguration deployed on WDS was not copied to the WEC

### ISSUE THREAD

**Issue by eaepstein** [kubestellar/kubestellar#1637]
### Describe the bug

scenario:
helm deployment of kar (https://github.com/IBM/kar) succeeds, but one of the components necessary to run kar applications is not being down-synced from WDS to WEC

### Steps To Reproduce

1. start KS as normal
2. clone kar repo and cd to .../kar/scripts
3. create a WEC as follows:
   a. helm --kube-context wds1 install kar helm/kar  -n kar-system  --create-namespace --set-string kar.injector.imageName=quay.io/ibm/kar-injector --set-string kar.injector.sidecarImageName=quay.io/ibm/kar-sidecar
   b. kubectl --context wds1 label namespace kar-system app.kubernetes.io/managed-by=Helm  app.kubernetes.io/instance=kar
   c. kubectl --context wds1 get secret kar.ibm.com.runtime-config -n kar-system -o yaml | sed "s/kar-system/default/g" | kubectl -n default create -f -
   d. kubectl --context wds1 label namespace default kar.ibm.com/enabled=true --overwrite
4. create a placement to deploy the components on a WEC, for example:
`kubectl --context wds1 apply -f - <<EOF
apiVersion: edge.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: kar-placement
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
	- matchLabels: {"app.kubernetes.io/managed-by":"Helm"}
	- matchLabels: {"app.kubernetes.io/instance":"kar"}
EOF`

At this point the kar-system components should be deployed and running on the WEC, but the MutatingWebhookConfiguration present on WDS will be missing from the WEC

### Expected Behavior

The MutatingWebhookConfiguration named kar-injector-webhook should exist on the WEC

**Comment by pdettori** [comment]
I was able to reproduce this issue following the steps above, and found that the Klusterlet on the WECs does not have enough RBAC permissions to handle the delivery of the `MutatingWebhookConfiguration`. 

```
kubectl --context imbs1 -n cluster1 get manifestwork admissionregistration.k8s.iov1-mutatingwebhookconfiguration--kar-injector-webhook  -o yaml

....
status:
  conditions:
  - lastTransitionTime: "2024-01-23T21:36:54Z"
    message: Failed to apply manifest work
    observedGeneration: 1
    reason: AppliedManifestWorkFailed
    status: "False"
    type: Applied
  - lastTransitionTime: "2024-01-23T21:36:55Z"
    message: 1 of 1 resources have unknown status
    observedGeneration: 1
    reason: ResourcesStatusUnknown
    status: Unknown
    type: Available
  resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2024-01-23T21:36:54Z"
        message: 'Failed to apply manifest: mutatingwebhookconfigurations.admissionregistration.k8s.io
          "kar-injector-webhook" is forbidden: User "system:serviceaccount:open-cluster-management-agent:klusterlet-work-sa"
          cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io"
          at the cluster scope'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
```

**Comment by pdettori** [comment]
It might be a OCM issue. According to https://open-cluster-management.io/concepts/manifestwork/#permission-setting-for-work-agent the Klusterlet by default has the following permissions:

```
All workload manifests are applied to the managed cluster by the work agent, and by default the work agent has the following permission for the managed cluster:

clusterRole admin(instead of the cluster-admin) to apply kubernetes common resources
managing customresourcedefinitions, but can not manage a specific custom resource instance
managing clusterrolebindings, rolebindings, clusterroles, roles, including the bind and escalate permission, this is why we can grant work-agent service account extra permissions using ManifestWork
```

**Comment by pdettori** [comment]
It appears that `clusterRole admin` does NOT have permissions for `mutatingwebhookconfigurations` in api group `admissionregistration.k8s.io`. 
[admin.txt](https://github.com/kubestellar/kubestellar/files/14032139/admin.txt)

**Comment by pdettori** [comment]
The suggested solution from OCM docs is one of:
1.  add permission on the managed cluster directly
2.  add permission on the hub cluster by another ManifestWork, 

I  did a quick test for the first approach with the script:

```shell
clusters=(cluster1 cluster2);
for cluster in "${clusters[@]}"; do
kubectl --context ${cluster} apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klusterlet-mutatingwebhook-access
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klusterlet-mutatingwebhook-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: klusterlet-mutatingwebhook-access
subjects:
- kind: ServiceAccount
  name: klusterlet-work-sa
  namespace: open-cluster-management-agent
EOF
done
```

and the error in the ManifestWork went away:
```
status:
  conditions:
  - lastTransitionTime: "2024-01-23T21:50:57Z"
    message: Apply manifest work complete
    observedGeneration: 1
    reason: AppliedManifestWorkComplete
    status: "True"
    type: Applied
  - lastTransitionTime: "2024-01-23T21:50:57Z"
    message: All resources are available
    observedGeneration: 1
    reason: ResourcesAvailable
    status: "True"
    type: Available
  resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2024-01-23T21:50:57Z"
        message: Apply manifest complete
        reason: AppliedManifestComplete
        status: "True"
        type: Applied
      - lastTransitionTime: "2024-01-23T21:50:57Z"
        message: Resource is available
        reason: ResourceAvailable
        status: "True"
        type: Available
      - lastTransitionTime: "2024-01-23T21:50:57Z"
        message: ""
        reason: NoStatusFeedbackSynced
        status: "True"
        type: StatusFeedbackSynced
      resourceMeta:
        group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        name: kar-injector-webhook
        namespace: ""
        ordinal: 0
        resource: mutatingwebhookconfigurations
        version: v1
      statusFeedback: {}
```      

and mutatingwebhookconfigurations.admissionregistration.k8s.io get delivered:
```
$ k --context cluster1 -n kar-system get mutatingwebhookconfigurations.admissionregistration.k8s.io 
NAME                   WEBHOOKS   AGE
kar-injector-webhook   1          69s
```
