### ISSUE TITLE
bug: PVCs created by a helm deployment on WDS block clean up of WDS when deployment is deleted by helm

### ISSUE THREAD

**Issue by eaepstein** [kubestellar/kubestellar#1638]
### Describe the bug

By design "helm delete" does not delete PVCs that were created by "helm create".
The result is that the PVC resource objects on WDS block KS from cleaning up the WDS.

### Steps To Reproduce

1. deploy kar as described in bug #1637 
2. remove the deployment with "helm --kube-context wds1 -n kar-system delete kar"

At this point the  kar-system namespace on WDS cannot be deleted.

### Expected Behavior

Since "helm delete" is designed to leave PVCs deployed, KS should do the same when doing "helm delete": clean up manifestwork and anything else created by the deployment.

**Comment by pdettori** [comment]
I have reproduced the issue and found that a PVC has a finalizer named `kubernetes.io/pvc-protection` that prevents it from being deleted until it is no longer used by any pods. Because we disabled many controllers in the kube-controller-manager for control planes of type `k8s`,  that finalizer never gets removed.

**Comment by pdettori** [comment]
Did some more digging and found that the controllers responsible for removing the finalizers from PV and PVCs when all attached pods are deleted are `pv-protection` and `pvc-protection`, and can be added back to the list of controllers started by the Kube-controller-manager.

**Comment by pdettori** [comment]
Run a quick test: 
- manually edited  kube-controller-manager for wds1 and enabled `pv-protection` and `pvc-protection`
- run step 1 and 2 above
- verified finalizer is removed and pvcs are removed.

Created issue https://github.com/kubestellar/kubeflex/issues/179 in KubeFlex to address this

**Comment by pdettori** [comment]
tested that the behavior of deleting via helm chart is exactly the same, both if I deploy from WDS or directly on the WEC:
Chart installed via WDS:
```
$ helm --kube-context wds1 delete kar -n kar-system
release "kar" uninstalled
(⎈|wds1:default)$ k --context cluster1 -n kar-system get pods,pvc,cm,secrets,mutatingwebhookconfigurations,deployments,statefulsets
NAME              READY   STATUS        RESTARTS   AGE
pod/kar-redis-0   1/1     Terminating   0          4h6m

NAME                                  STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/kar-redis-pvc   Terminating   pvc-19fa1e10-9a75-448c-a7d9-53b0b2e9816f   1Gi        RWO            standard       4h6m

NAME                         DATA   AGE
configmap/kube-root-ca.crt   1      4h7m
...
(⎈|wds1:default)$ k --context cluster1 -n kar-system get pods,pvc,cm,secrets,mutatingwebhookconfigurations,deployments,statefulsets
NAME                         DATA   AGE
configmap/kube-root-ca.crt   1      4h8m
```
2. Chart installed directly on cluster1
```
(⎈|cluster1:N/A)$ helm --kube-context cluster1 delete -n kar-system kar
release "kar" uninstalled
(⎈|cluster1:N/A)$ k --context cluster1 -n kar-system get pods,pvc,cm,secrets,mutatingwebhookconfigurations,deployments,statefulsets
NAME              READY   STATUS        RESTARTS   AGE
pod/kar-redis-0   1/1     Terminating   0          94s

NAME                                  STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/kar-redis-pvc   Terminating   pvc-ec18020f-3d24-4745-9b32-8c9419aafb42   1Gi        RWO            standard       94s

NAME                         DATA   AGE
configmap/kube-root-ca.crt   1      4h11m
...
(⎈|cluster1:N/A)$ k --context cluster1 -n kar-system get pods,pvc,cm,secrets,mutatingwebhookconfigurations,deployments,statefulsets
NAME                         DATA   AGE
configmap/kube-root-ca.crt   1      4h15m
```

**Comment by pdettori** [comment]
This is fixed in https://github.com/kubestellar/kubeflex/pull/181 and available in new KF release v0.4.1. Creating a PR to update pre-reqs for this.

**Comment by MikeSpreitzer** [comment]
BTW, what puts that finalizer _on_ the PVC?

**Comment by pdettori** [comment]
@MikeSpreitzer it's the Kube API server. This can be easily tested as follows:

```
kflex create cp1
k --context kind-kubeflex -n cp1-system scale deployment kube-controller-manager --replicas 0
kubectl --context cp1 apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
EOF

k get pvc my-pvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"my-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}}}}
  creationTimestamp: "2024-01-26T02:35:17Z"
  finalizers:
  - kubernetes.io/pvc-protection
 ...
 ```
