### ISSUE TITLE
bug: objects don't downsync after delete and recreate of placement object

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1710]
### Describe the bug

Creating a placement + deployment on WDS downsync the deployment to the WEC.  If we then delete placement followed by create placement, then the deployment won't always downsync.  It does not help if we add a sleep(10) or a get deployment from WEC and confirm there is none between the delete and create placement.

### Steps To Reproduce
See a comment below on how to reproduce from scratch.  But the gist of it is captured in the following instructions:
```
$ kubectl --context wds1 delete placements nginx-placement; kubectl --context cluster1 get deployment -n nginx; kubectl --context wds1 create -f - <<EOF
apiVersion: control.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: nginx-placement
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
    - matchLabels: {"app.kubernetes.io/name":"nginx"}
EOF
$ kubectl --context cluster1 get deployments -n nginx


```
### Expected Behavior

Deployment gets downsynced.

**Comment by effi-ofer** [comment]
This is holding back PR #1713

**Comment by pdettori** [comment]
is there any useful info in the kubestellar controller manager log ? also, can you check what happens with manifestworks on imbs1 for cluster1 namespace?

**Comment by effi-ofer** [comment]
To reproduce from the command line do the following:
```
cd test/e2e/common
./cleanup.sh
./setup-kubestellar.sh
kubectl --context wds1 apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:latest
        ports:
        - containerPort: 80
EOF
```
Then run in a loop:
```
kubectl --context wds1 delete placements nginx-placement; kubectl --context cluster1 get deployment -n nginx; kubectl --context wds1 create -f - <<EOF
apiVersion: control.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: nginx-placement
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
    - matchLabels: {"app.kubernetes.io/name":"nginx"}
EOF
kubectl --context cluster1 get deployments -n nginx
```
