### ISSUE TITLE
bug: invalid generated manifest work name for clusterrolebinding with name "system:controller:xqueuejob-controller"

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1849]
### Describe the bug

This error was found with kubestellar v0.20.0 for a clusterrolebinding with name `controller:xqueuejob-controller`

```
controller.go:684] "Error delivering object to mailbox" err="ManifestWork.work.open-cluster-management.io \"rbac.authorization.k8s.iov1-clusterrolebinding--system:controller:xqueuejob-controller\" is invalid: metadata.name: Invalid value: \"rbac.authorization.k8s.iov1-clusterrolebinding--system:controller:xqueuejob-controller\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')" logger="Binding"
```

### Steps To Reproduce

1. Create a v0.20.0 kubestellar instance
2. Create an clusterrolebinding on the wds as follows:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: mcad-controller
    meta.helm.sh/release-namespace: mcad
  labels:
    app.kubernetes.io/managed-by: Helm
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:xqueuejob-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:xqueuejob-controller
subjects:
- kind: ServiceAccount
  name: mcad-controller
  namespace: mcld
 ``` 
 3. Create a matching bindingpolicy, e.g.
 ```
 apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: mcad-agent-placement
spec:
  clusterSelectors:
  - matchLabels:
      location-group: edge
  downsync:
  - apiGroup: ""
    objectNames:
    - mcad
    - ks-test
    resources:
    - namespaces
  - apiGroup: ""
    namespaces:
    - mcad
    objectNames:
    - mcad-controller
    resources:
    - serviceaccounts
  - apiGroup: ""
    namespaces:
    - mcad
    objectNames:
    - mcad-agents-config
    resources:
    - secrets
  - apiGroup: apiextensions.k8s.io
    objectNames:
    - appwrappers.mcad.ibm.com
    - quotasubtrees.ibm.com
    - queuejobs.mcad.ibm.com
    - schedulingspecs.mcad.ibm.com
    resources:
    - customresourcedefinitions
  - apiGroup: rbac.authorization.k8s.io
    objectNames:
    - custom-metrics-resource-reader
    - custom-metrics-server-resources
    - system:controller:xqueuejob-controller
    - custom-metrics-resource-reader
    - custom-metrics:system:auth-delegator
    - hpa-controller-custom-metrics
    - system:controller:xqueuejob-controller
    - system:controller:xqueuejob-controller-edit
    - system:controller:xqueuejob-controller-kube-scheduler
    resources:
    - clusterroles
    - clusterrolebindings
  - apiGroup: rbac.authorization.k8s.io
    namespaces:
    - mcad
    - data-science
    objectNames:
    - '*'
    resources:
    - rolebindings
    - roles
  - apiGroup: ""
    namespaces:
    - mcad
    objectNames:
    - custom-metrics-apiserver
    resources:
    - services
  - apiGroup: ""
    namespaces:
    - mcad
    objectNames:
    - '*'
    resources:
    - configmaps
  - apiGroup: ""
    namespaces:
    - mcad
    objectNames:
    - '*'
    resources:
    - serviceaccounts
  - apiGroup: apps
    namespaces:
    - mcad
    objectNames:
    - mcad-controller
    resources:
    - deployments
  wantSingletonReportedState: true
 ``` 
 4. Check the log of the kubestellar controller manager for the error to show up
 

### Expected Behavior

Should generate a name that passes the validation and manifest work shows up on imbs1
