### ISSUE TITLE
bug: website says "contributing" is different from, and also a subset of, "development"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1926]
### Describe the bug

In docs/mkdocs.yml I see this:

```yaml
...
nav:
  - Home:
      - Overview: index.md 
      - Readme: readme.md
      - Architecture: direct/architecture.md
      - Development:
          - Contributors: direct/contributor.md
          - Packaging: direct/packaging.md
          - Pre-reqs: direct/pre-reqs.md
          - Release Process: direct/release.md
      - Usage:
          - User Guide: direct/user-guide.md
          - Examples: direct/examples.md
      - Release-notes: direct/release-notes.md
  - Contributing: 
      - Guidelines: Contribution guidelines/CONTRIBUTING.md
...
```

### Steps To Reproduce

Go to the website and see.

### Expected Behavior

"contributor" = "developer of KubeStellar".
Recognition that _users_ of KubeStellar are commonly "developers" of something else.
