### ISSUE TITLE
bug: same BindingPolicy, created in 2 different wds' pointing at the same clusterselector (location-group: edge) only applies to the first wds

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1982]
### Describe the bug

wds1, wds2
both are labeled "location-group: edge"

both get the same bindingpolicy

```
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: sealed-secrets-bindingpolicy
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels:
      location-group: edge
  downsync:
  - objectSelectors:
    - matchLabels: 
        app.kubernetes.io/part-of: sealed-secrets
```

manifestworks will only be created for wds1 because it was created first. wds2 bindings will be ignored.

I would, if I could, use "name: wds1" and "name: wds2" - but this would require more source files or string replacement.

### Steps To Reproduce

create wds1, wds2
label both "location-group: edge"

install sealed-secrets from bitnami (or any package for that matter) on wds1 and wds2

add BindingPolicy

```
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: sealed-secrets-bindingpolicy
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels:
      location-group: edge
  downsync:
  - objectSelectors:
    - matchLabels: 
        app.kubernetes.io/part-of: sealed-secrets
```

watch wds1 get populated and wds2 get nothing

if you change clusterselector to "name: wds1" and "name: wds2", then bindings work properly.

### Expected Behavior

I would like the BindingPolicy to take effect on both clusters because they are both in the group edge.
