### ISSUE TITLE
bug:  CustomTransform example in user guide is missing the apiVersion

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#2112]
### Describe the bug

The example provided is the user guide is missing the apiVersion:

```
kind: CustomTransform
metadata:
  name: example
spec:
  apiGroup: batch
  resource: jobs
  remove:
  - "$.spec.suspend"
```

### Steps To Reproduce

Look at the user guide in https://docs.kubestellar.io/release-0.22.0/direct/user-guide/

### Expected Behavior

Should have the apiVersion
