### ISSUE TITLE
bug: user guide should be more clear about limitations of CustomTransform JSONPath syntax

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#2113]
### Describe the bug

The user guide should have enough information to explain how to deal with an array of values; for example it is not clear from the docs if rules below:

``` 
apiVersion: control.kubestellar.io/v1alpha1
kind: CustomTransform
metadata:
  name: workflow
spec:
  apiGroup: argoproj.io
  resource: workflows
  remove:
  - $.spec.suspend
  - $.metadata.labels["workflows.argoproj.io/completed"]
  - $.metadata.labels["workflows.argoproj.io/phase"]
  - $.metadata.labels["pipeline/runid"]
```  

can also be written as:

```
apiVersion: control.kubestellar.io/v1alpha1
kind: CustomTransform
metadata:
  name: workflow
spec:
  apiGroup: argoproj.io
  resource: workflows
  remove:
  - $.spec.suspend
  - $.metadata.labels["workflows.argoproj.io/completed","workflows.argoproj.io/phase","pipeline/runid" ]
```

(the answer I have got from the maintainers is NO, but I could not infer that from the documentation)  

### Steps To Reproduce

Look at the docs

### Expected Behavior

Should be more clear about the array syntax expression.
