### ISSUE TITLE
bug: It takes several minutes to delete an object from the WEC

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#2287]
### Describe the bug

So first, my hosting cluster and a WEC are created with K3D and running on MAC. On the hosting cluster I create a job with a label matching binding policy of the WEC. The job gets pulled to the WEC where it runs to completion. The status is pushed up to the hosting cluster. The label matching the bindingpolicy is deleted. The job is not listed in the Bindings object, but it is listed in the manifestwork in its1. It takes several minutes before the object is eventually deleted from the WEC. Sometimes it can take ~20 minutes. I've checked the transport-controller and kubestellar-controller-manager logs for errors and did not see anything alarming.

Versions of things:

export KUBESTELLAR_VERSION=0.23.0
export OCM_STATUS_ADDON_VERSION=0.2.0-rc10
export OCM_TRANSPORT_PLUGIN=0.1.11

K8s:
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+k3s1

Snapshot of job's pods on the WEC:

```
NAME                     READY   STATUS      RESTARTS   AGE
sample-job-q6kmw-7jgq5   0/1     Completed   0          13m
sample-job-q6kmw-d7969   0/1     Completed   0          13m
sample-job-q6kmw-272k5   0/1     Completed   0          13m
```

The above job completed in about 80s from the start.

BindingPolicy:

```
  clusterSelectors:
  - matchLabels:
      location-group: edge
      name: cluster1
  downsync:
  - objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster1
  wantSingletonReportedState: true
```

The label that was removed after job completion was: kubestellar.io/cluster: cluster1

The Job:

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: default
  labels:
    kubestellar.io/cluster: cluster1
spec:
  parallelism: 3
  completions: 3

  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["50s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
          limits:
            memory: "200Mi"
            cpu: 1
      restartPolicy: Never
```

### Steps To Reproduce

1. Setup Hosting cluster with wds of type host and a WEC.
2. Create bindingpolicy for the WEC using spec as above.
3. Use a job from above or add a label to a sample job that matches the BP
4. Create a job on the hosting cluster and allow it to finish on the WEC
5. Edit the job on the hosting cluster and remove the label added in step 3
6. Watch the job pods on the WEC ( in my case these linger for several minutes) 

### Expected Behavior

When a label is removed from a job, it should be removed from the WEC fairly quickly

### Want to contribute?

- [ ] I would like to work on this issue.
