### ISSUE TITLE
bug: Kubestellar Example scenarios all fail on Linux due to bad syntax for tail

### ISSUE THREAD

**Issue by eaepstein** [kubestellar/kubestellar#2367]
### Describe the bug

Creation of binding policies all fail because "tail +3c" is invalid syntax in Linux. 
The correct syntax is "tail -c +3"

### Steps To Reproduce

For example, running:
```
kubectl --context "$wec1_context" apply -f - <<EOF
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: nginx-bpolicy
spec:
  clusterSelectors:
  - matchLabels: {$(echo "$label_query_both" | tr , $'\n' | while IFS="=" read key val; do echo -n ", \"$key\": \"$val\""; done | tail +3c)}
  downsync:
  - objectSelectors:
    - matchLabels: {"app.kubernetes.io/name":"nginx"}
EOF
```
returns:
`tail: cannot open '+3c' for reading: No such file or directory`

### Expected Behavior

The examples should work on Linux

### Want to contribute?

- [ ] I would like to work on this issue.
