### ISSUE TITLE
bug: singleton reported state return of Job object happens only after completion

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2436]
### Describe the bug

I am told that when Kueue is integrated with KubeStellar, with a BindingPolicy that requests singleton reported state return for a Job object, the `.status` of the Job in the WDS does not show anything from the WEC until the Job completes. This is unexpected, because a Job object has some `.status` content throughout its lifecycle.

### Steps To Reproduce

See above for a rough outline. @cwiklik is the expert. @waltforme has recently reproduced the problem.

### Expected Behavior

The `.status` of the Job propagates from the WEC to the WDS throughout the Job object's lifetime.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

@waltforme has reported some observations in #1851, specifically:

- https://github.com/kubestellar/kubestellar/issues/1851#issuecomment-2329760947 - watch of a Job object when using Kueue without KubeStellar (i.e., single-cluster scenario).
- https://github.com/kubestellar/kubestellar/issues/1851#issuecomment-2332166094 - watch of a Job object when using Kueue with KubeStellar.

**Comment by MikeSpreitzer** [comment]
Looking at that watch log from Kueue+KubeStellar (https://github.com/kubestellar/kubestellar/issues/1851#issuecomment-2332166094), I see the `.status` become empty in the version starting at line 805. Annoyingly, the `metadata.managedFields` does not show which manager deleted the `.status` content --- ManagedFields only shows ownership of the _existing_ parts of the object.

It would help to see the corresponding log from the controller-manager, with `-v` set to 5.

**Comment by MikeSpreitzer** [comment]
In the Job starting at line 1087, the KubeStellar controller-manager has propagated running `.status` from WEC to WDS:

```yaml
status:
  active: 3
  ready: 3
  startTime: "2024-09-05T12:48:51Z"
  terminating: 0
  uncountedTerminatedPods: {}
```

In the Job starting at line 1237, the FieldManager named "k3s" has revised just one field, `.status.ready`, to the value 0 (which is right from its local point of view):

```yaml
status:
  active: 3
  ready: 0
  startTime: "2024-09-05T12:48:51Z"
  terminating: 0
  uncountedTerminatedPods: {}
```

**Comment by MikeSpreitzer** [comment]
In the Job starting at line 1395, the KubeStellar controller-manager propagated new `.status`, not including `.status.ready`; following is the ManagedFields entry for that.

```yaml
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:startTime: {}
        f:terminating: {}
        f:uncountedTerminatedPods:
          .: {}
          f:succeeded:
            .: {}
            v:"40c50334-82f2-41d4-9f50-f0370f548749": {}
            v:"63a93b81-10ce-445f-a2a4-aa7b25fe800c": {}
            v:"3861993f-aa89-4f70-8061-c0ab10394b2d": {}
    manager: controller-manager
    operation: Update
    subresource: status
    time: "2024-09-05T12:49:11Z"
```

The `.status.ready` continues to show the value written by k3s:

```yaml
status:
  ready: 0
  startTime: "2024-09-05T12:48:51Z"
  terminating: 0
  uncountedTerminatedPods:
    succeeded:
    - 63a93b81-10ce-445f-a2a4-aa7b25fe800c
    - 40c50334-82f2-41d4-9f50-f0370f548749
    - 3861993f-aa89-4f70-8061-c0ab10394b2d
```

**Comment by MikeSpreitzer** [comment]
That is quickly followed by the Job starting at line 1561.

```yaml
  - apiVersion: batch/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:completionTime: {}
        f:conditions: {}
        f:startTime: {}
        f:succeeded: {}
        f:terminating: {}
        f:uncountedTerminatedPods: {}
    manager: controller-manager
    operation: Update
    subresource: status
    time: "2024-09-05T12:49:11Z"
```

```yaml
status:
  completionTime: "2024-09-05T12:49:11Z"
  conditions:
  - lastProbeTime: "2024-09-05T12:49:11Z"
    lastTransitionTime: "2024-09-05T12:49:11Z"
    status: "True"
    type: Complete
  ready: 0
  startTime: "2024-09-05T12:48:51Z"
  succeeded: 3
  terminating: 0
  uncountedTerminatedPods: {}
```
