### ISSUE TITLE
bug: no kubeconfig context for its1 was found: context its1 not found for control plane its1

### ISSUE THREAD

**Issue by wendy-ha18** [kubestellar/kubestellar#2777]
### Describe the bug

I believe this issue will be helpful for someone else so just want to document it here.
Slack thread discussion on [#kuberstellar-dev](https://kubernetes.slack.com/archives/C058SUSL5AA/p1738333771598949) channel.

I got this issue multiple times with its1 context after running command [Use Core Helm chart to initialize KubeFlex and create ITS and WDS](https://docs.kubestellar.io/release-0.25.1/direct/get-started/#use-core-helm-chart-to-initialize-kubeflex-and-create-its-and-wds) . When ran `kflex ctx --overwrite-existing-context its1` , it's always output `no kubeconfig context for its1 was found: context its1 not found for control plane its1`
I have reviewed these documents to try to find any relevant issues with its1 context have been reported before couldn't find anyone.
- https://docs.kubestellar.io/release-0.25.1/direct/troubleshooting/
- https://github.com/kubestellar/kubestellar/issues?q=is%3Aissue%20state%3Aopen%20its1.
- kubestellar_version: this issue has showed up on both: [v0.26.0-alpha.5](https://github.com/kubestellar/kubestellar/releases/tag/v0.26.0-alpha.5) and [v0.25.1](https://github.com/kubestellar/kubestellar/releases/tag/v0.25.1)

-------------------------------
```
@wendy-ha18 ➜ /workspaces/ui (main) $ bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/v0.26.0-alpha.5/scripts/create-kind-cluster-with-SSL-passthrough.sh) --name kubeflex --port 9443
Creating "kubeflex" kind cluster with SSL passthrougn and 9443 port mapping...
No kind clusters found.
Creating cluster "kubeflex" ...
 ✓ Ensuring node image (kindest/node:v1.32.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kubeflex"
You can now use your cluster with:

kubectl cluster-info --context kind-kubeflex

Thanks for using kind! 😊
Installing an nginx ingress...
namespace/ingress-nginx created
serviceaccount/ingress-nginx created
serviceaccount/ingress-nginx-admission created
role.rbac.authorization.k8s.io/ingress-nginx created
role.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrole.rbac.authorization.k8s.io/ingress-nginx created
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission created
rolebinding.rbac.authorization.k8s.io/ingress-nginx created
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
configmap/ingress-nginx-controller created
service/ingress-nginx-controller created
service/ingress-nginx-controller-admission created
deployment.apps/ingress-nginx-controller created
job.batch/ingress-nginx-admission-create created
job.batch/ingress-nginx-admission-patch created
ingressclass.networking.k8s.io/nginx created
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission created
Patching nginx ingress to enable SSL passthrough...
deployment.apps/ingress-nginx-controller patched
Waiting for nginx ingress with SSL passthrough to be ready...
pod/ingress-nginx-controller-5f897d6454-ddrmt condition met
Setting context to "kind-kubeflex"...
Switched to context "kind-kubeflex".
@wendy-ha18 ➜ /workspaces/ui (main) $ helm upgrade --install ks-core oci://ghcr.io/kubestellar/kubestellar/core-chart --version 0.26.0-alpha.5 --set-json='ITSes=[{"name":"its1"}]' --set-json='WDSes=[{"name":"wds1"}]' --set-json='verbosity.default=5'
Release "ks-core" does not exist. Installing it now.
Pulled: ghcr.io/kubestellar/kubestellar/core-chart:0.26.0-alpha.5
Digest: sha256:47d9a84841c3523d3785524f7c9b0fb92481cbec0dd6e789ad191f0c44e64d60
NAME: ks-core
LAST DEPLOYED: Fri Jan 31 15:27:38 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
For your convenience you will probably want to add contexts to your
kubeconfig named after the non-host-type control planes (WDSes and
ITSes) that you just created (a host-type control plane is just an
alias for the KubeFlex hosting cluster). You can do that with the
following `kflex` commands; each creates a context and makes it the
current one. See
https://github.com/kubestellar/kubestellar/blob/0.26.0-alpha.5/docs/content/direct/core-chart.md#kubeconfig-files-and-contexts-for-control-planes
for a way to do this without using `kflex`.
Start by setting your current kubeconfig context to the one you used
when installing this chart.

kubectl config use-context $the_one_where_you_installed_this_chart
kflex ctx --set-current-for-hosting # make sure the KubeFlex CLI's hidden state is right for what the Helm chart just did

kflex ctx --overwrite-existing-context its1
kflex ctx --overwrite-existing-context wds1

Finally, you can use `kflex ctx` to switch back to the kubeconfig
context for your KubeFlex hosting cluster.
@wendy-ha18 ➜ /workspaces/ui (main) $ kubectl config use-context kind-kubeflex # this is here only to remind you, it will already be the current context if you are following this recipe exactly
ure the KubeFlex CLI's hidden state is right for what the Helm chart just did
kflex ctx --overwrite-existing-context wds1
kflex ctx --overwrite-existing-context its1Switched to context "kind-kubeflex".
@wendy-ha18 ➜ /workspaces/ui (main) $ kflex ctx --set-current-for-hosting # make sure the KubeFlex CLI's hidden state is right for what the Helm chart just did
✔ Checking for saved hosting cluster context...
✔ Switching to hosting cluster context...
@wendy-ha18 ➜ /workspaces/ui (main) $ kflex ctx --overwrite-existing-context wds1
trying to load new context wds1 from server...
✔ Overwriting existing context for control plane
✔ Switching to context wds1...
@wendy-ha18 ➜ /workspaces/ui (main) $ kflex ctx --overwrite-existing-context its1
no kubeconfig context for its1 was found: context its1 not found for control plane its1
✔ Overwriting existing context for control plane
trying to load new context its1 from server...
```
`wds1` was successfully created and its context was switched, but `its1` is missing.

```
@wendy-ha18 ➜ /workspaces/ui (main) $ kubectl config get-contexts
CURRENT   NAME            CLUSTER         AUTHINFO        NAMESPACE
*         kind-kubeflex   kind-kubeflex   kind-kubeflex   
          wds1            wds1-cluster    wds1-admin      default
@wendy-ha18 ➜ /workspaces/ui (main) $ helm get values ks-core --all -o yaml
CLUSTERADM_VERSION: 0.9.0
HELM_VERSION: 3.16.1
ITSes:
- name: its1
InstallPCHs: true
KUBECTL_VERSION: 1.31.0
KUBESTELLAR_VERSION: 0.26.0-alpha.5
OCM_STATUS_ADDON_VERSION: 0.2.0-rc14
WDSes:
- name: wds1
kubeflex-operator:
  domain: localtest.me
  externalPort: "9443"
  global: {}
  hostContainer: kubeflex-control-plane
  install: true
  installPostgreSQL: true
  isOpenShift: "false"
  verbosity: 2
status_agent:
  hub_burst: 10
  hub_qps: 5
  local_burst: 10
  local_qps: 5
  log_flush_frequency: 5s
  logging_format: text
  metrics_bind_addr: :8080
  pprof_bind_addr: :8082
  vmodule: ""
status_controller: {}
transport_controller:
  max_num_wrapped: 1
  max_size_wrapped: 512000
  metrics_bind_addr: :8090
  pprof_bind_addr: :8092
  transport_burst: 10
  transport_qps: 5
  wds_burst: 10
  wds_qps: 5
verbosity:
  default: 5
```

![Image](https://github.com/user-attachments/assets/116d2a3f-af9a-449b-a0b1-1c5cce185d57)

### Steps To Reproduce

Follow https://docs.kubestellar.io/release-0.25.1/direct/get-started/, from beginning until [Use Core Helm chart to initialize KubeFlex, recognize ITS, and create WDS ](https://docs.kubestellar.io/release-0.25.1/direct/start-from-ocm/#use-core-helm-chart-to-initialize-kubeflex-recognize-its-and-create-wds) step.

### Expected Behavior

N/A

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

N/A
