### ISSUE TITLE
feature: Add logic to the KubeStellar controller to map back the status to the objects READY values

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#2809]
### Feature Description

Currently a user needs to look at the status objects to figure out if a certain objects was actually propagated to the WECs etc.

I would be nice to add logic to bring back the states to the original object in the WDS.

Specifically, the values READ x/y should depict the actual summarized state.
For example, with `n`  replicas going to `m` clusters, `y` should be equal to `n*m`

### Proposed Solution

 I'm not sure

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I am trying to understand the general request here. It sounds like a new feature to me: filling in the reported state of objects with an approximation of the reported state from all the WECs even when the number of them is not 1. If we attempt this then I think that the answer should work even for kinds of objects that _we_ do not know about.

I think that this request is motivated by ArgoCD's display of `Deployment` objects. I am trying to understand exactly what is the approximation function being requested for these. You can see the definition of the status section of a `Deployment` at https://github.com/kubernetes/api/blob/v0.29.14/apps/v1/types.go#L480-L517 . You will see that it has several integer-valued counter fields. Filling one in with the sum over the same field in all the WECs is going to be confusing when compared with the `spec.replicas`. I think that average (rounded down) would be better than sum. The rounding down works well when scaling up, but is overly optimistic when scaling down. Also, there is a set of "conditions", which have boolean values. I suppose the most obvious way to approximate is to combine with AND, on the grounds that these are usually defined in a positive way. Following is an example of the conditions for a `Deployment`.

```yaml
  - lastTransitionTime: "2025-02-24T23:14:46Z"
    lastUpdateTime: "2025-02-24T23:14:46Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-24T23:14:42Z"
    lastUpdateTime: "2025-02-24T23:14:46Z"
    message: ReplicaSet "coredns-76f75df574" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
```

There are also other fields, such as `observedGeneration`.

**Comment by Pardhasardhiraob29** [comment]
Hi! I'm new to open source and would love to make my first contribution. If this issue is still open would love work upon it.
Thanks a lot!
/assign

**Comment by Rupam-It** [comment]
![Image](https://github.com/user-attachments/assets/fe466173-6436-4d61-9c65-63830233b22a)
this can be our proposed solution with this as a file structure!
```
pkg/
  status/
    aggregation/           # New package for aggregation logic
      types.go             # Define interfaces and common types
      deployment.go        # Deployment-specific aggregation
      statefulset.go       # StatefulSet-specific aggregation
      service.go           # Service-specific aggregation
      daemonset.go         # DaemonSet-specific aggregation
      generic.go           # Generic handler for unknown types
      util.go              # Utility functions
```

**Comment by clubanderson** [comment]
see also https://github.com/kubestellar/ui/issues/1432

**Comment by clubanderson** [comment]
@francostellari @Rupam-It please add number of "paid interns: 1" and number of "unpaid interns: X"

replace X with the number of unpaid interns you will accept into the project

**Comment by francostellari** [comment]
> [@francostellari](https://github.com/francostellari) [@Rupam-It](https://github.com/Rupam-It) please add number of "paid interns: 1" and number of "unpaid interns: X"
> 
> replace X with the number of unpaid interns you will accept into the project

added 1+1

**Comment by francostellari** [comment]
I would like to further elaborate on a specific case to clarify the current observed shortcomings and desired behavior.

**Note that this example is based on a `deployment` object type but it is desirable to extend the behavior to all (if possible)/many object types.**

Assume that we have 1 ITS `its1` and 1 WDS `wds1` and 2 WECs `cluster1` and `cluster2` as discussed in the get started procedures.

Furthermore, we create a sample nginx deployment object in `wds1`.

**Scenario 1: current behavior is fine**

If the there is no `BindingPolicy` with an object selector matching the deployment, then the  deployment object in the `wds1` show as:
```bash
$ k get deployments -A
NAMESPACE   NAME               READY   UP-TO-DATE   AVAILABLE   AGE
nginx       nginx-deployment   0/1     0            0           27h
```

and its `.status` field is empty:
```yaml
status: {}
```

I think that this is an expected behavior, informing the user that the deployment is not downsynced anywhere and nothing is happening.

**Scenario 2: current behavior is fine**

If we create a `BindingPolicy` selecting the deployment object in `wds1` and 1 and only 1 target WEC cluster (e.g., `cluster1`), we can also use the singleton status reporting feature `wantSingletonReportedState: true` of KubeStellar to get the desired behavior.

See: https://docs.kubestellar.io/release-0.28.0/direct/example-scenarios/#scenario-4-singleton-status

In this care:

```bash
$ k get deployments -A
NAMESPACE   NAME               READY   UP-TO-DATE   AVAILABLE   AGE
nginx       nginx-deployment   1/1     1            1           27h
```

And the `.status` field of the deployment is populated:

```yaml
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-22T21:06:15Z"
    lastUpdateTime: "2025-08-22T21:06:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-22T21:06:13Z"
    lastUpdateTime: "2025-08-22T21:06:15Z"
    message: ReplicaSet "nginx-deployment-6c644f6bd9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

I think that this is an expected behavior, informing the user that the deployment is indeed running on one of the WECs.

**Scenario 3: current behavior is not good**

If we apply a `BindingPolicy` matching the nginx deployment object in the `wds1`  to multiple target WECs (e.g., `cluser1` and `cluster2`), then **we cannot use the singleton status reporting anymore**.

The user could create a `StatusCollector` object and use it in the `BindingPolicy` to obtain a `CombinedStatus`.
See: https://docs.kubestellar.io/release-0.28.0/direct/combined-status/

However, the status of the deployment object in the `wds1` would not inform the user that the object was downsynced to the WECs and working fine:

```bash
$ k get deployments -A
NAMESPACE   NAME               READY   UP-TO-DATE   AVAILABLE   AGE
nginx       nginx-deployment   0/1     0            0           27h
```

By looking at the nginx deployment object in the `wds1`, a user cannot immediately distinguish between scenario 1, where the deployment is not running on any WEC, and scenario 3, where the deployment is running on 2 WECs.
I believe this is an undesirable behavior.

Ideally, in this scenario, the status of the object should be update to to report:

```yaml
status:
  availableReplicas: <total number of available downsyced replicas across all the target WECs> (e.g. = 1 replica * 2 clusters)
  readyReplicas: <total number of ready downsyced replicas across all the target WECs> (e.g. = 1 replica * 2 clusters)
  replicas: <total number of replicas that the binding policyes are requesting across all the target WECs> (e.g. = 1 replica * 2 clusters)
  updatedReplicas: <total number of updated downsyced replicas across all the target WECs> (e.g. = 1 replica * 2 clusters)
```
