### ISSUE TITLE
bug: CI testing succeeded for PR that broke some tests

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#817]
### Describe the bug

The merge of PR #814 made some of the docs-ecutable tests start failing.  Indeed, the branch in that PR --- the `new-issue-559-560` branch in https://github.com/fileppb/edge-mc, which pointed to commit 0e6e3f90c12020bcba9cc409c2278f8a4e8c6108 at the time --- also fails those tests.  And yet the testing in CI succeeded!  See https://github.com/kubestellar/kubestellar/actions/runs/5626329356 for an example.  See https://github.com/kubestellar/kubestellar/pull/814#issuecomment-1646894692 and the later comments for an explanation of the problem introduced and what is mysterious about the CI testing.

### Steps To Reproduce

See above.

### Expected Behavior

For a PR that breaks some tests, running those tests on the merge of that PR does not succeed.

**Comment by fileppb** [comment]
will work on this tomorrow

**Comment by fileppb** [comment]
@MikeSpreitzer @clubanderson I also noticed that there are references in the .md's to SyncTarget.workload.kcp.io and Location.scheduling.kcp.io that need to be replaced with references to the edge.kcp.io api group. Will take a look at all the .md's.

**Comment by clubanderson** [comment]
@MikeSpreitzer @fileppb 
 I would like to get the CI to fail for 814.  It appears that the simple checkout that the workflow (for all docs-ecutable files) is referencing the base branch and not the the latest commit in any given PR.  To fix this I would like to test by
1. unmerging PR 814
2. add (at line 50 of docs-ecutable-example1.yml)
“with:
          ref: ${{ github.event.pull_request.head.sha }}”
3. push a commit.

what do you think about this approach?  Or do you see another way to test the fix?

**Comment by clubanderson** [comment]
I am recommending (for all docs-ecutables)

```
 - uses: actions/checkout@v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        if: github.event_name == 'pull_request'
    
      - uses: actions/checkout@v3.5.3
        if: github.event_name != 'pull_request'
```
