### ISSUE TITLE
bug: namespace is not deleted on execution cluster when deleted in a space 

### ISSUE THREAD

**Issue by ronenkat** [kubestellar/kubestellar#896]
### Describe the bug

I created a edge-placement followed by creating a namespace, a deployment and a service (in the namespace).
The namespace and resources were successfully down-synced.
I delete the namespace in the KS space. The deployment and service were deleted in the execution cluster, but the namespace was not deleted and contains two CM and 6 secrets. 

```
apiVersion: edge.kcp.io/v1alpha1
kind: EdgePlacement
metadata:
  name: edge-placement-test1
spec:
  locationSelectors:
  - matchLabels: {"env":"cloud1"}
  namespaceSelector:
    matchLabels: {"workload":"cloud1"}
  nonNamespacedObjects:
  - apiGroup: apis.kcp.io
    resources: [ "apibindings" ]
    resourceNames: [ "bind-kubernetes", "bind-apps" ]
  upsync:
  - apiGroup: "group1.test"
    resources: ["sprockets", "flanges"]
    namespaces: ["orbital"]
    names: ["george", "cosmo"]
  - apiGroup: "group2.test"
    resources: ["cogs"]
    names: ["william"]
```

### Steps To Reproduce

```
% kubectl apply -f ~/repos/kubestellar/k8s/edge-placement-cloud1-test1.yaml
edgeplacement.edge.kcp.io/edge-placement-test1 created
% kubectl apply -f ~/repos/kubestellar/k8s/workload.yaml                        
namespace/test1 created
deployment.apps/deployment created
service/controlplane created
kubectl delete ns test1
namespace "test1" deleted
```

### Expected Behavior

The namespace test1 would be deleted in the execution cluster

### Additional Context

Kubestellar was run in an openshift cluster
syncer was run in an openshift cluster (same cluster as above)
