### ISSUE TITLE
feature: Use the community kcp helm chart to deploy kcp

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#995]
Rather than deploying kcp in our current chart, we want to use the community helm chart for kcp. As part of this feature we need to:

- [x] ensure that the community chart works as expected for deploying to upstream Kubernetes as well as OpenShift (this includes also providing configuration examples for  KS use cases)
- [ ] update the current KS helm chart to use the community kcp helm chart

**Comment by pdettori** [comment]
When testing the kcp helm chart, @MikeSpreitzer run into this issue: https://github.com/kcp-dev/helm-charts/issues/52.
This issue is originated because containers run as non-root and so we need to provide a fsFroup that matches the uid (USER field) of the container image, that for kcp is 65532 - see https://github.com/kcp-dev/kcp/blob/main/Dockerfile#L62C7-L63.

After investigating the issue, I found that the latest tagged chart, with version kcp-0.2.5 does not have the following  section:
```yaml
securityContext:
        # this matches the group id as set in the kcp Dockerfile.
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
```
This was fixed in main, which has that section - https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/templates/kcp.yaml#L255C1-L259C23.

But the chart is not installed from main but from the tagged release, which is published in gh-pages at  https://kcp-dev.github.io/helm-charts.   As a workaround, we can just automate the patching of the deployment in our installation scripts, however we should ask the owners of the helm chart project if they could publish a new release from main.

**Comment by pdettori** [comment]
Repeated the test of installing the chart on a fresh OCP installation. Here are the steps to get it to work:

1. Install cert-manager (from OCP Console-Operators-OperatorHub)
2. Once installed go to “Installed Operators” and create an instance of a ClusterIssuer
3. Download the helm chart values yaml for the chart from https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/values.yaml
4. Update the following values:
    - externalHostname (need to know the endpoint for the OCP ingress, for example if the chart release is named "kcp" and the OCP domain name is "kflex1.kubeflex.org" the hostname would be `kcp.apps.kflex1.kubeflex.org`)
    - kcpFrontProxy.openshiftRoute.enabled: true
5. Install the chart following the instructions in https://github.com/kcp-dev/helm-charts/tree/main, e.g.
```shell
helm repo add kcp https://kcp-dev.github.io/helm-charts
helm install kcp kcp/kcp --values ./values.yaml
```
6. Create a patch.yaml file with the following content:
```yaml
spec:
  template:
    spec:
      securityContext:
        fsGroup: 65532
      containers:
      - name: kcp
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
```
7. apply the patch with the command:
```shell
oc patch deployment kcp --patch-file patch.yaml
```
8. Verify all pods run:
```shell
$ oc get pods
NAME                               READY   STATUS    RESTARTS   AGE
etcd-0                             1/1     Running   0          28m
etcd-1                             1/1     Running   0          28m
etcd-2                             1/1     Running   0          28m
kcp-59754f4d-h8hlm                 1/1     Running   0          25m
kcp-front-proxy-655b9fb698-j7d89   1/1     Running   0          28m
```
